In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import sys
from pathlib import Path

_ = Path().resolve().parent.parent # Add [...]\MS960_MachineLearning\Projeto2\run to PYTHONPATH
sys.path.insert(0, str(_))

from Projeto2.neural_network.neural import *
from Projeto2.neural_network.plots import *
from Projeto2.run import cfg

## Reading data

In [2]:
data_folder = "../data/test/"
res_folder  = "../data/results/keep/"

df_images   = pd.read_csv(data_folder+"images.csv", index_col=0)
df_labels   = pd.read_csv(data_folder+"labels.csv", index_col=0)

total_costs = pd.read_csv(res_folder+"costs.csv", index_col=0)
thetas_12   = pd.read_csv(res_folder+"thetas_12.csv", index_col=0)
thetas_23   = pd.read_csv(res_folder+"thetas_23.csv", index_col=0)

In [3]:
df_images

,image_1,image_3,image_4,image_5,image_6,image_7,image_8,image_9,image_10,image_11,...,image_4991,image_4992,image_4993,image_4994,image_4995,image_4996,image_4997,image_4998,image_4999,image_5000
pixel_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pixel_2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pixel_3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pixel_4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pixel_5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
pixel_396,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pixel_397,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pixel_398,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pixel_399,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pixel_400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Calculate the data for the test

In [5]:
class_matrix = classification_matrix(df_labels, cfg.LABELS)

activations  = activation_layer(df_images, class_matrix, thetas=[thetas_12, thetas_23])

cost         = cost_function_sigmoid(activations, class_matrix)

In [6]:
classification_labels = pd.DataFrame( activations[-1].idxmax(axis="index") , columns=['value'])

## Correct classification

In [7]:
for i in range( classification_labels.shape[0] ):
    classification_labels.iloc[i] = int( classification_labels.iloc[i][0].split("label_")[1] )
correct_classification = 1*(classification_labels == df_labels)

correct_classification = pd.concat([correct_classification, df_labels, classification_labels], axis=1)
correct_classification.columns = ['correto', 'original', 'atribuido']

correct_classification

            correto  original atribuido
image_1           1        10        10
image_3           1        10        10
image_4           1        10        10
image_5           1        10        10
image_6           1        10        10
...             ...       ...       ...
image_4996        0         9         3
image_4997        0         9         2
image_4998        0         9         3
image_4999        0         9         4
image_5000        0         9        10

[4500 rows x 3 columns]

In [14]:
ratio = 100 * correct_classification['correto'].value_counts(normalize=True)
print(ratio)
print(f"\nCORRECTS = {round(ratio[1],2)}%")

1    60.311111
0    39.688889
Name: correto, dtype: float64

CORRECTS = 60.31%

In [15]:
cost

              cost
label_1   0.133776
label_2   0.210936
label_3   0.219399
label_4   0.201964
label_5   0.290963
label_6   0.164492
label_7   0.178198
label_8   0.278412
label_9   0.276601
label_10  0.106920